version: '3'

services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    privileged: true
    volumes:
      - ./mcm_shared_volume/:/shared
    environment:
      - SHARED_DIRECTORY=/shared
      # Uncomment these if needed
      # - READ_ONLY=true
      # - SYNC=true
      # - PERMITTED=10.11.12.*
    ports:
      - "2049:2049"
